# Generated by Django 3.1 on 2021-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mshall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champs2011to2012sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pictures')),
                ('medal', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('competition', models.CharField(max_length=75)),
                ('field', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Champs2012to2013socult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pictures')),
                ('medal', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('competition', models.CharField(max_length=75)),
                ('field', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Champs2016to2017sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pictures')),
                ('medal', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('competition', models.CharField(max_length=75)),
                ('field', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Champs2017to2018sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pictures')),
                ('medal', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('competition', models.CharField(max_length=75)),
                ('field', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Champs2018to2019sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pictures')),
                ('medal', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('competition', models.CharField(max_length=75)),
                ('field', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Champs2019to2020socult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pictures')),
                ('medal', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('competition', models.CharField(max_length=75)),
                ('field', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Champs2019to2020tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pictures')),
                ('medal', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('competition', models.CharField(max_length=75)),
                ('field', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Champs2020to2021tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pictures')),
                ('medal', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('competition', models.CharField(max_length=75)),
                ('field', models.CharField(max_length=75)),
            ],
        ),
    ]
