# Generated by Django 3.2.3 on 2021-05-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mshall', '0003_auto_20210519_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='gcnotices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='notices')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gnrlnotices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='notices')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hallnotices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='notices')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='messnotices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='notices')),
                ('text', models.TextField()),
            ],
        ),
    ]
